// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY1OfKJBNevAxkL0ur8Cb_zMMBq5eFfak',
    appId: '1:425837714550:web:30ffa2d936c877fed09357',
    messagingSenderId: '425837714550',
    projectId: 'internhelper',
    authDomain: 'internhelper.firebaseapp.com',
    storageBucket: 'internhelper.firebasestorage.app',
    measurementId: 'G-R9ZNGZHT9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPsrjJPlMHYtgbnxr2NHnbQS6s9uf9CU',
    appId: '1:425837714550:android:bfbe3b9b3f4984d7d09357',
    messagingSenderId: '425837714550',
    projectId: 'internhelper',
    storageBucket: 'internhelper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtlZ4ZMP_jucs-Kf_9Ut0zL74NfQAEXIY',
    appId: '1:425837714550:ios:c8f8570823352f8cd09357',
    messagingSenderId: '425837714550',
    projectId: 'internhelper',
    storageBucket: 'internhelper.firebasestorage.app',
    iosClientId: '425837714550-ba7o80nvdqcgv7m18c526ischciuls2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.exemple',
  );
}
